from src.Calculo_numerico_Diferenciacion_y_metodos_de_Heron_y_de_Newton import \
    (test_derivada,
     test_derivadas,
     test_derivadaFinaSeno,
     test_raiz,
     test_casiIgual,
     test_raizI,
     test_puntoCero,
     test_puntoCeroI,
     test_raizCuadrada,
     test_raizCubica,
     test_arcoseno,
     test_arcocoseno,
     test_inversa,
     test_inversas)

test_derivada()
test_derivadas()
test_derivadaFinaSeno()
test_raiz()
test_casiIgual()
test_raizI()
test_puntoCero()
test_puntoCeroI()
test_raizCuadrada()
test_raizCubica()
test_arcoseno()
test_arcocoseno()
test_inversa()
test_inversas()
